### PR TITLE
add set/get Scanmode

### PR DESCRIPTION
**Pull request by AppWerft**
scanMode added
onScanResult gives list of UUIDs

### CODE REVIEW

**Comment by m1ga** [comment]
Thanks, but can you please update your Repository before you make the pull request and just include the necessary files (e.g. only the TiBluetoothModule.java) so it's easier to merge.

**Comment by AppWerft** [comment]
OK Michael, I have commited local , the pushed to my forked repo and the in my repo on github the PR requested. Is it the right way? (I'm newbie in github stuff)

**Comment by m1ga** [comment]
Go to your local folder and run `git pull https://github.com/hansemannn/ti.bluetooth master` that will fetch the latest files. Then do your changes and just run `git add android/src/ti/bluetooth/TiBluetoothModule.java` so it will only add this file and not your personal configuration and other binary stuff. The push the file and it will update this PR

**Comment by m1ga** [comment]
But I can compare the Java file and merge the changes locally and update the file since it shouldn't be that much if that's easier. I'll have a look at it later when I'm at my machine

**Comment by AppWerft** [comment]
nice and thanks.

**Comment by m1ga** [comment]
added the id's to the event. From the documentation:
`This method does not start a service discovery procedure to retrieve the UUIDs from the remote device. Instead, the local cached copy of the service UUIDs are returned.`
So it might be empty without `fetchUuidsWithSdp` but I'll have to test the changes tomorrow, no BLE device around me at the moment :)

**Pull request closed without merging**
